const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(state,live=true,tenant='active'){const core={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/platform-access-core.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:core,Response,Request,Headers});const rows=state===null?[]:[{id:'u',state,version:'1'}];class Pool{listenerCount(){return 1} on(){} async query(sql){if(state==='outage')throw Error('database offline');if(sql.includes('FROM tenants'))return {rows:[{status:tenant,deleted_at:null}]};if(sql.includes('FROM tenant_memberships'))return {rows:[{id:'m'}]};return {rows:sql.includes('FROM "session"')?(live?[{id:'s'}]:[]):rows}}}const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/platform-access.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,require:n=>n==='pg'?{Pool}:core,globalThis:{},process:{env:{PLATFORM_ACCESS_POLICY_ENABLED:'false'}},Response});return exports;}
for(const state of ['suspended','blocked','deleted','unknown',null])test('global account '+state+' denies sessions with optional policy disabled',async()=>{assert.equal(await load(state).platformSessionAllowed('u','s'),false);assert.equal(await load(state).platformAccessAllowed('u'),false)});
test('active global account and live session remain allowed',async()=>assert.equal(await load('active').platformSessionAllowed('u','s'),true));

test('expired or revoked session denies an active account',async()=>assert.equal(await load('active',false).platformSessionAllowed('u','s'),false));
test('identity database outage fails closed with 503',async()=>assert.rejects(()=>load('outage').platformSessionAllowed('u','s'),e=>e.status===503));

for(const state of ['pending','unknown','suspended','cancelled'])test('nonactive tenant '+state+' cannot resolve account access',async()=>assert.equal(await load('active',true,state).platformAccessAllowed('u','t'),false));
test('active tenant membership remains allowed',async()=>assert.equal(await load('active').platformAccessAllowed('u','t'),true));
